services:
  - type: web
    name: loomserver
    runtime: python-3.12.4
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn loomserver.wsgi"
    envVars:
      SECRET_KEY:
        generate: true
      DATABASE_URL:
        fromDatabase:
          name: loom-db
          property: connectionString

databases:
  - name: loom-db
    plan: free
